In [1]:
import pandas as pd
import numpy as np

In [2]:
# pd.set_option('display.max_columns', None)  #DELETE

In [3]:
fifa = pd.read_csv('copy_fifa21_train.csv')
display(fifa.head())

fifa.shape

,ID,Name,Age,Nationality,Club,BP,Position,Team & Contract,Height,Weight,...,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,OVA
0,184383,A. Pasche,26,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,188044,Alan Carvalho,30,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,184431,S. Giovinco,33,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,233796,J. Evans,22,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,234799,Y. Demoncy,23,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65

(11701, 101)

In [4]:
fifa.duplicated().sum()

0

In [5]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(fifa.dtypes)

ID                    int64
Name                 object
Age                   int64
Nationality          object
Club                 object
BP                   object
Position             object
Team & Contract      object
Height               object
Weight               object
foot                 object
Growth                int64
Joined               object
Loan Date End        object
Value                object
Wage                 object
Release Clause       object
Contract             object
Attacking             int64
Crossing              int64
Finishing             int64
Heading Accuracy      int64
Short Passing         int64
Volleys             float64
Skill                 int64
Dribbling             int64
Curve               float64
FK Accuracy           int64
Long Passing          int64
Ball Control          int64
Movement              int64
Acceleration          int64
Sprint Speed          int64
Agility             float64
Reactions             int64
Balance             float64
Power                 int64
Shot Power            int64
Jumping             float64
Stamina               int64
Strength              int64
Long Shots            int64
Mentality             int64
Aggression            int64
Interceptions       float64
Positioning         float64
Vision              float64
Penalties             int64
Composure           float64
Defending             int64
Marking               int64
Standing Tackle       int64
Sliding Tackle      float64
Goalkeeping           int64
GK Diving             int64
GK Handling           int64
GK Kicking            int64
GK Positioning        int64
GK Reflexes           int64
Total Stats           int64
Base Stats            int64
W/F                  object
SM                   object
A/W                  object
D/W                  object
IR                   object
PAC                   int64
SHO                   int64
PAS                   int64
DRI                   int64
DEF                   int64
PHY                   int64
Hits                 object
LS                   object
ST                   object
RS                   object
LW                   object
LF                   object
CF                   object
RF                   object
RW                   object
LAM                  object
CAM                  object
RAM                  object
LM                   object
LCM                  object
CM                   object
RCM                  object
RM                   object
LWB                  object
LDM                  object
CDM                  object
RDM                  object
RWB                  object
LB                   object
LCB                  object
CB                   object
RCB                  object
RB                   object
GK                   object
OVA                   int64
dtype: object

In [6]:
fifa.select_dtypes(include=np.number)

,ID,Age,Growth,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,...,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY,OVA
0,184383,26,1,258,54,47,43,70,44.0,286,...,6,1682,357,69,51,63,63,51,60,64
1,188044,30,0,365,66,79,76,68,76.0,375,...,16,1961,412,83,75,68,82,33,71,77
2,184431,33,0,336,73,76,34,78,75.0,424,...,3,1925,404,80,77,78,86,27,56,80
3,233796,22,13,242,44,42,58,62,36.0,259,...,12,1527,329,57,44,54,57,57,60,59
4,234799,23,8,249,49,37,61,68,34.0,280,...,15,1664,360,66,44,60,64,60,66,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,232504,25,5,224,62,24,51,59,28.0,248,...,14,1589,347,75,28,56,59,60,69,65
11697,214680,27,4,84,12,14,13,29,16.0,96,...,72,1123,387,72,67,66,72,40,70,70
11698,221489,22,8,286,64,66,51,64,41.0,291,...,16,1603,337,76,60,60,72,26,43,67
11699,146717,26,7,254,64,66,51,73,NaN,284,...,24,1429,400,72,63,70,72,57,66,68
11700,236507,22,9,289,43,64,65,64,53.0,267,...,8,1607,336,79,62,56,67,24,48,64

In [7]:
fifa.select_dtypes(include=object)

,Name,Nationality,Club,BP,Position,Team & Contract,Height,Weight,foot,Joined,...,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK
0,A. Pasche,Switzerland,FC Lausanne-Sport,CM,CM CDM,FC Lausanne-Sport 2015 ~ 2020,"5'9""",161lbs,Right,"Jul 1, 2015",...,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1
1,Alan Carvalho,China PR,Beijing Sinobo Guoan FC,ST,ST LW LM,"Beijing Sinobo Guoan FC Dec 31, 2020 On Loan","6'0""",159lbs,Right,"Jan 16, 2015",...,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2
2,S. Giovinco,Italy,Al Hilal,CAM,CAM CF,Al Hilal 2019 ~ 2022,"5'4""",134lbs,Right,"Jan 31, 2019",...,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2
3,J. Evans,Wales,Swansea City,CDM,CDM CM,Swansea City 2016 ~ 2021,"5'10""",152lbs,Right,"Jul 1, 2016",...,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2
4,Y. Demoncy,France,US Orléans Loiret Football,CDM,CDM CM,US Orléans Loiret Football 2018 ~ 2021,"5'11""",150lbs,Right,"Jul 1, 2018",...,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,B. Böðvarsson,Iceland,Jagiellonia Białystok,LB,LB,Jagiellonia Białystok 2018 ~ 2021,"6'1""",168lbs,Left,"Feb 8, 2018",...,60+2,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2
11697,G. Gallon,France,ESTAC Troyes,GK,GK,ESTAC Troyes 2019 ~ 2022,"6'1""",174lbs,Right,"Jul 1, 2019",...,26+2,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2
11698,J. Flores,Chile,CD Antofagasta,RM,LM CAM RM,CD Antofagasta 2019 ~ 2024,"5'6""",143lbs,Right,"Jan 23, 2019",...,44+2,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2
11699,Anderson Silva,Brazil,Barnsley,CM,NaN,Barnsley 2010,"6'2""",179lbs,Right,NaN,...,68+0,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0
11700,T. Conechny,Argentina,Portland Timbers,CAM,ST CAM LM,Portland Timbers 2019 ~ 2020,"5'7""",143lbs,Left,"Jul 22, 2019",...,43+2,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2

In [9]:
fifa1 = fifa.drop(columns=['Wage', 'Position','Growth', 'Value', 'ID', 'Name', 'Nationality', 'Club', 'Team & Contract', "Joined", "Loan Date End", "Release Clause", "Contract", "A/W", "D/W"], axis=1)

In [10]:
cols1 = []
for column in fifa1.columns:
    cols1.append(column.lower())
cols1
fifa1.columns = cols1

fifa1.head()

fifa1

,age,bp,height,weight,foot,attacking,crossing,finishing,heading accuracy,short passing,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,CM,"5'9""",161lbs,Right,258,54,47,43,70,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,30,ST,"6'0""",159lbs,Right,365,66,79,76,68,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,33,CAM,"5'4""",134lbs,Right,336,73,76,34,78,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,22,CDM,"5'10""",152lbs,Right,242,44,42,58,62,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,23,CDM,"5'11""",150lbs,Right,249,49,37,61,68,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,"6'1""",168lbs,Left,224,62,24,51,59,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,27,GK,"6'1""",174lbs,Right,84,12,14,13,29,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,22,RM,"5'6""",143lbs,Right,286,64,66,51,64,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,26,CM,"6'2""",179lbs,Right,254,64,66,51,73,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,22,CAM,"5'7""",143lbs,Left,289,43,64,65,64,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [11]:
fifa1['hits'] = fifa1['hits'].apply(pd.to_numeric, errors='coerce')

In [12]:
fifa1.select_dtypes(include=np.number)

,age,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,dribbling,curve,...,total stats,base stats,pac,sho,pas,dri,def,phy,hits,ova
0,26,258,54,47,43,70,44.0,286,61,44.0,...,1682,357,69,51,63,63,51,60,3.0,64
1,30,365,66,79,76,68,76.0,375,83,78.0,...,1961,412,83,75,68,82,33,71,44.0,77
2,33,336,73,76,34,78,75.0,424,85,89.0,...,1925,404,80,77,78,86,27,56,73.0,80
3,22,242,44,42,58,62,36.0,259,54,41.0,...,1527,329,57,44,54,57,57,60,7.0,59
4,23,249,49,37,61,68,34.0,280,64,44.0,...,1664,360,66,44,60,64,60,66,4.0,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,224,62,24,51,59,28.0,248,57,49.0,...,1589,347,75,28,56,59,60,69,3.0,65
11697,27,84,12,14,13,29,16.0,96,17,15.0,...,1123,387,72,67,66,72,40,70,3.0,70
11698,22,286,64,66,51,64,41.0,291,71,57.0,...,1603,337,76,60,60,72,26,43,6.0,67
11699,26,254,64,66,51,73,NaN,284,74,NaN,...,1429,400,72,63,70,72,57,66,3.0,68
11700,22,289,43,64,65,64,53.0,267,64,41.0,...,1607,336,79,62,56,67,24,48,8.0,64

In [13]:
fifa1.select_dtypes(include=object)

,bp,height,weight,foot,w/f,sm,ir,ls,st,rs,...,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk
0,CM,"5'9""",161lbs,Right,4 ★,2★,1 ★,58+1,58+1,58+1,...,59+1,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1
1,ST,"6'0""",159lbs,Right,3 ★,4★,2 ★,77+0,77+0,77+0,...,53+2,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2
2,CAM,"5'4""",134lbs,Right,4 ★,4★,2 ★,73+2,73+2,73+2,...,56+2,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2
3,CDM,"5'10""",152lbs,Right,2 ★,2★,1 ★,50+2,50+2,50+2,...,58+2,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2
4,CDM,"5'11""",150lbs,Right,2 ★,3★,1 ★,56+2,56+2,56+2,...,64+2,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,LB,"6'1""",168lbs,Left,3 ★,2★,1 ★,48+2,48+2,48+2,...,60+2,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2
11697,GK,"6'1""",174lbs,Right,2 ★,1★,1 ★,28+2,28+2,28+2,...,26+2,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2
11698,RM,"5'6""",143lbs,Right,3 ★,3★,1 ★,62+2,62+2,62+2,...,44+2,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2
11699,CM,"6'2""",179lbs,Right,3 ★,1★,3 ★,68+0,68+0,68+0,...,68+0,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0
11700,CAM,"5'7""",143lbs,Left,3 ★,3★,1 ★,64+2,64+2,64+2,...,43+2,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2

In [14]:
fifa1['w/f'] = fifa1['w/f'].str.rstrip("★").astype(float)
fifa1['sm'] = fifa1['sm'].str.rstrip("★").astype(float)
fifa1['ir'] = fifa1['ir'].str.rstrip("★").astype(float)
fifa1

,age,bp,height,weight,foot,attacking,crossing,finishing,heading accuracy,short passing,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,CM,"5'9""",161lbs,Right,258,54,47,43,70,...,59+1,59+1,59+1,58+1,54+1,54+1,54+1,58+1,15+1,64
1,30,ST,"6'0""",159lbs,Right,365,66,79,76,68,...,53+2,53+2,57+2,53+2,48+2,48+2,48+2,53+2,18+2,77
2,33,CAM,"5'4""",134lbs,Right,336,73,76,34,78,...,56+2,56+2,59+2,53+2,41+2,41+2,41+2,53+2,12+2,80
3,22,CDM,"5'10""",152lbs,Right,242,44,42,58,62,...,58+2,58+2,56+2,57+2,58+2,58+2,58+2,57+2,14+2,59
4,23,CDM,"5'11""",150lbs,Right,249,49,37,61,68,...,64+2,64+2,64+2,63+2,61+2,61+2,61+2,63+2,15+2,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,"6'1""",168lbs,Left,224,62,24,51,59,...,60+2,60+2,63+2,63+2,61+2,61+2,61+2,63+2,16+2,65
11697,27,GK,"6'1""",174lbs,Right,84,12,14,13,29,...,26+2,26+2,25+2,24+2,26+2,26+2,26+2,24+2,69+2,70
11698,22,RM,"5'6""",143lbs,Right,286,64,66,51,64,...,44+2,44+2,49+2,45+2,35+2,35+2,35+2,45+2,17+2,67
11699,26,CM,"6'2""",179lbs,Right,254,64,66,51,73,...,68+0,68+0,66+0,64+0,60+0,60+0,60+0,64+0,25+0,68
11700,22,CAM,"5'7""",143lbs,Left,289,43,64,65,64,...,43+2,43+2,46+2,44+2,36+2,36+2,36+2,44+2,15+2,64

In [15]:
cols = ['ls','st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk']
for col in cols:
    fifa1[col] = fifa1[col].apply(lambda x:x.split("+")[0])

In [16]:
fifa1[cols] = fifa1[cols].apply(pd.to_numeric, errors='coerce')

In [17]:
fifa1

,age,bp,height,weight,foot,attacking,crossing,finishing,heading accuracy,short passing,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,CM,"5'9""",161lbs,Right,258,54,47,43,70,...,59,59,59,58,54,54,54,58,15,64
1,30,ST,"6'0""",159lbs,Right,365,66,79,76,68,...,53,53,57,53,48,48,48,53,18,77
2,33,CAM,"5'4""",134lbs,Right,336,73,76,34,78,...,56,56,59,53,41,41,41,53,12,80
3,22,CDM,"5'10""",152lbs,Right,242,44,42,58,62,...,58,58,56,57,58,58,58,57,14,59
4,23,CDM,"5'11""",150lbs,Right,249,49,37,61,68,...,64,64,64,63,61,61,61,63,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,"6'1""",168lbs,Left,224,62,24,51,59,...,60,60,63,63,61,61,61,63,16,65
11697,27,GK,"6'1""",174lbs,Right,84,12,14,13,29,...,26,26,25,24,26,26,26,24,69,70
11698,22,RM,"5'6""",143lbs,Right,286,64,66,51,64,...,44,44,49,45,35,35,35,45,17,67
11699,26,CM,"6'2""",179lbs,Right,254,64,66,51,73,...,68,68,66,64,60,60,60,64,25,68
11700,22,CAM,"5'7""",143lbs,Left,289,43,64,65,64,...,43,43,46,44,36,36,36,44,15,64

In [18]:
fifa1['height'] = (fifa1['height'].str.extract(r'(\d+)\'\s*(\d+)"').astype(float).mul([12*2.54, 2.54]).sum(axis=1))

In [19]:
fifa1['weight'] = fifa1['weight'].str.rstrip("lbs").astype(float)/2.2

In [20]:
fifa1

,age,bp,height,weight,foot,attacking,crossing,finishing,heading accuracy,short passing,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,CM,175.26,73.181818,Right,258,54,47,43,70,...,59,59,59,58,54,54,54,58,15,64
1,30,ST,182.88,72.272727,Right,365,66,79,76,68,...,53,53,57,53,48,48,48,53,18,77
2,33,CAM,162.56,60.909091,Right,336,73,76,34,78,...,56,56,59,53,41,41,41,53,12,80
3,22,CDM,177.80,69.090909,Right,242,44,42,58,62,...,58,58,56,57,58,58,58,57,14,59
4,23,CDM,180.34,68.181818,Right,249,49,37,61,68,...,64,64,64,63,61,61,61,63,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,185.42,76.363636,Left,224,62,24,51,59,...,60,60,63,63,61,61,61,63,16,65
11697,27,GK,185.42,79.090909,Right,84,12,14,13,29,...,26,26,25,24,26,26,26,24,69,70
11698,22,RM,167.64,65.000000,Right,286,64,66,51,64,...,44,44,49,45,35,35,35,45,17,67
11699,26,CM,187.96,81.363636,Right,254,64,66,51,73,...,68,68,66,64,60,60,60,64,25,68
11700,22,CAM,170.18,65.000000,Left,289,43,64,65,64,...,43,43,46,44,36,36,36,44,15,64

In [21]:
nulls_df = pd.DataFrame(round(fifa1.isna().sum()/len(fifa1),4)*100)
nulls_df
nulls_df = nulls_df.reset_index()
nulls_df
nulls_df.columns = ['header_name', 'percent_nulls']
nulls_df

   header_name  percent_nulls
0          age            0.0
1           bp            0.0
2       height            0.0
3       weight            0.0
4         foot            0.0
..         ...            ...
81          cb            0.0
82         rcb            0.0
83          rb            0.0
84          gk            0.0
85         ova            0.0

[86 rows x 2 columns]

In [22]:
fifa1.select_dtypes(include=np.number)

,age,height,weight,attacking,crossing,finishing,heading accuracy,short passing,volleys,skill,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,175.26,73.181818,258,54,47,43,70,44.0,286,...,59,59,59,58,54,54,54,58,15,64
1,30,182.88,72.272727,365,66,79,76,68,76.0,375,...,53,53,57,53,48,48,48,53,18,77
2,33,162.56,60.909091,336,73,76,34,78,75.0,424,...,56,56,59,53,41,41,41,53,12,80
3,22,177.80,69.090909,242,44,42,58,62,36.0,259,...,58,58,56,57,58,58,58,57,14,59
4,23,180.34,68.181818,249,49,37,61,68,34.0,280,...,64,64,64,63,61,61,61,63,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,185.42,76.363636,224,62,24,51,59,28.0,248,...,60,60,63,63,61,61,61,63,16,65
11697,27,185.42,79.090909,84,12,14,13,29,16.0,96,...,26,26,25,24,26,26,26,24,69,70
11698,22,167.64,65.000000,286,64,66,51,64,41.0,291,...,44,44,49,45,35,35,35,45,17,67
11699,26,187.96,81.363636,254,64,66,51,73,NaN,284,...,68,68,66,64,60,60,60,64,25,68
11700,22,170.18,65.000000,289,43,64,65,64,53.0,267,...,43,43,46,44,36,36,36,44,15,64

In [23]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(fifa.dtypes)

ID                    int64
Name                 object
Age                   int64
Nationality          object
Club                 object
BP                   object
Position             object
Team & Contract      object
Height               object
Weight               object
foot                 object
Growth                int64
Joined               object
Loan Date End        object
Value                object
Wage                 object
Release Clause       object
Contract             object
Attacking             int64
Crossing              int64
Finishing             int64
Heading Accuracy      int64
Short Passing         int64
Volleys             float64
Skill                 int64
Dribbling             int64
Curve               float64
FK Accuracy           int64
Long Passing          int64
Ball Control          int64
Movement              int64
Acceleration          int64
Sprint Speed          int64
Agility             float64
Reactions             int64
Balance             float64
Power                 int64
Shot Power            int64
Jumping             float64
Stamina               int64
Strength              int64
Long Shots            int64
Mentality             int64
Aggression            int64
Interceptions       float64
Positioning         float64
Vision              float64
Penalties             int64
Composure           float64
Defending             int64
Marking               int64
Standing Tackle       int64
Sliding Tackle      float64
Goalkeeping           int64
GK Diving             int64
GK Handling           int64
GK Kicking            int64
GK Positioning        int64
GK Reflexes           int64
Total Stats           int64
Base Stats            int64
W/F                  object
SM                   object
A/W                  object
D/W                  object
IR                   object
PAC                   int64
SHO                   int64
PAS                   int64
DRI                   int64
DEF                   int64
PHY                   int64
Hits                 object
LS                   object
ST                   object
RS                   object
LW                   object
LF                   object
CF                   object
RF                   object
RW                   object
LAM                  object
CAM                  object
RAM                  object
LM                   object
LCM                  object
CM                   object
RCM                  object
RM                   object
LWB                  object
LDM                  object
CDM                  object
RDM                  object
RWB                  object
LB                   object
LCB                  object
CB                   object
RCB                  object
RB                   object
GK                   object
OVA                   int64
dtype: object

In [24]:
fifa1.select_dtypes(include=object)

        bp   foot
0       CM  Right
1       ST  Right
2      CAM  Right
3      CDM  Right
4      CDM  Right
...    ...    ...
11696   LB   Left
11697   GK  Right
11698   RM  Right
11699   CM  Right
11700  CAM   Left

[11701 rows x 2 columns]

In [25]:
round(fifa1.isna().sum()/len(fifa1),4)*100

age       0.0
bp        0.0
height    0.0
weight    0.0
foot      0.0
         ...
cb        0.0
rcb       0.0
rb        0.0
gk        0.0
ova       0.0
Length: 86, dtype: float64

In [26]:
fifa1.isna().sum()

age       0
bp        0
height    0
weight    0
foot      0
         ..
cb        0
rcb       0
rb        0
gk        0
ova       0
Length: 86, dtype: int64

In [27]:
replace_NaN = nulls_df[nulls_df['percent_nulls']>1]['header_name']  
print(replace_NaN.values)

['composure']

In [28]:
fifa1

,age,bp,height,weight,foot,attacking,crossing,finishing,heading accuracy,short passing,...,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,ova
0,26,CM,175.26,73.181818,Right,258,54,47,43,70,...,59,59,59,58,54,54,54,58,15,64
1,30,ST,182.88,72.272727,Right,365,66,79,76,68,...,53,53,57,53,48,48,48,53,18,77
2,33,CAM,162.56,60.909091,Right,336,73,76,34,78,...,56,56,59,53,41,41,41,53,12,80
3,22,CDM,177.80,69.090909,Right,242,44,42,58,62,...,58,58,56,57,58,58,58,57,14,59
4,23,CDM,180.34,68.181818,Right,249,49,37,61,68,...,64,64,64,63,61,61,61,63,15,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11696,25,LB,185.42,76.363636,Left,224,62,24,51,59,...,60,60,63,63,61,61,61,63,16,65
11697,27,GK,185.42,79.090909,Right,84,12,14,13,29,...,26,26,25,24,26,26,26,24,69,70
11698,22,RM,167.64,65.000000,Right,286,64,66,51,64,...,44,44,49,45,35,35,35,45,17,67
11699,26,CM,187.96,81.363636,Right,254,64,66,51,73,...,68,68,66,64,60,60,60,64,25,68
11700,22,CAM,170.18,65.000000,Left,289,43,64,65,64,...,43,43,46,44,36,36,36,44,15,64

In [29]:
columns_drop = nulls_df[nulls_df['percent_nulls']<1]['header_name']  
print(columns_drop.values)

['age' 'bp' 'height' 'weight' 'foot' 'attacking' 'crossing' 'finishing'
 'heading accuracy' 'short passing' 'volleys' 'skill' 'dribbling' 'curve'
 'fk accuracy' 'long passing' 'ball control' 'movement' 'acceleration'
 'sprint speed' 'agility' 'reactions' 'balance' 'power' 'shot power'
 'jumping' 'stamina' 'strength' 'long shots' 'mentality' 'aggression'
 'interceptions' 'positioning' 'vision' 'penalties' 'defending' 'marking'
 'standing tackle' 'sliding tackle' 'goalkeeping' 'gk diving'
 'gk handling' 'gk kicking' 'gk positioning' 'gk reflexes' 'total stats'
 'base stats' 'w/f' 'sm' 'ir' 'pac' 'sho' 'pas' 'dri' 'def' 'phy' 'hits'
 'ls' 'st' 'rs' 'lw' 'lf' 'cf' 'rf' 'rw' 'lam' 'cam' 'ram' 'lm' 'lcm' 'cm'
 'rcm' 'rm' 'lwb' 'ldm' 'cdm' 'rdm' 'rwb' 'lb' 'lcb' 'cb' 'rcb' 'rb' 'gk'
 'ova']

In [30]:
fifa1['position'].value_counts(dropna=False)

KeyError: 'position'

In [ ]:
fifa1['position']=fifa1['position'].fillna('CB')

In [ ]:
fifa1['composure'].value_counts(dropna=False)

In [ ]:
median_composure = fifa1['composure'].median()
median_composure

In [ ]:
fifa1['composure'] = fifa1['composure'].fillna(median_composure)

In [ ]:
nulls_df = pd.DataFrame(round(fifa1.isna().sum()/len(fifa1),4)*100)
nulls_df
nulls_df = nulls_df.reset_index()
nulls_df
nulls_df.columns = ['header_name', 'percent_nulls']
nulls_df

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(nulls_df)

In [ ]:
 fifa1.isna().sum().sum()

In [ ]:
fifa1= fifa1.dropna()
fifa1

In [ ]:
fifa1.isna().sum().sum()

### PROCESSING DATA.

#### Dealing with outliers.

In [ ]:
categorial_heads = fifa1.select_dtypes(include=['object']).columns.tolist()
print(categorial_heads)

In [ ]:
fifa1['position'].value_counts()

In [ ]:
fifa1 = fifa1.drop('position', axis=1)

### Normalization.

In [ ]:
import seaborn as sns
numericals = fifa1.select_dtypes(include=np.number)

In [ ]:
correlations_matrix = numericals.corr() # displaying the correlation matrix
correlations_matrix

In [ ]:
sns.heatmap(correlations_matrix, annot=True) # displaying the heatmap
plt.show()

In [ ]:
import pandas as pd

# Define the columns to check for correlation
columns_to_check = ['rw', 'lw', 'cf', 'rf', 'lf', 'rs', 'ls', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb']

# Calculate the correlation matrix
correlations = fifa1[columns_to_check].corr()

# Find pairs with correlation > 0.9
high_corr = []
for i in range(len(correlations.columns)):
    for j in range(i):
        if abs(correlations.iloc[i, j]) > 0.9:
            colname1 = correlations.columns[i]
            colname2 = correlations.index[j]
            high_corr.append((colname1, colname2))

# Print the pairs with high correlation
print(high_corr)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
y = fifa1['ova'] #defining x-y split
X = fifa1.drop(['ova'], axis=1)
X_num = X.select_dtypes(include = np.number)

In [ ]:
transformer = MinMaxScaler().fit(X_num) 
x_normalized = transformer.transform(X_num)
print(x_normalized.shape)
x_normalized1 = pd.DataFrame(x_normalized, columns=X_num.columns)
x_normalized1

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn import linear_model

In [ ]:
X_cat = fifa1.select_dtypes(include=object)

In [ ]:
#categorical features and numerical ones are going to be treated differently
X_num = X.select_dtypes(include = np.number)
X_cat = X.select_dtypes(include = object)

In [ ]:
X_cat

In [ ]:
encoder = OneHotEncoder(drop='first').fit(X_cat)

cols = encoder.get_feature_names_out(input_features=X_cat.columns)

X_cat_encode = pd.DataFrame(encoder.transform(X_cat).toarray(),columns=cols)

X_cat_encode.head()

In [ ]:
X_cat_encode.shape

In [ ]:
###Concatenating

In [ ]:
X = pd.concat([X_cat_encode, x_normalized1], axis=1)
X

In [ ]:
###Spliting the data ibto test and train samples

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [ ]:
lm = linear_model.LinearRegression()
lm.fit(X_train,y_train)

In [ ]:
from sklearn.metrics import r2_score
predictions = lm.predict(X_train)
r2_score(y_train, predictions)

In [ ]:
predictions

In [ ]:
predictions_test = lm.predict(X_test)
r2_score(y_test, predictions_test)

In [ ]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,predictions_test)
mse

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test,predictions_test))
rmse

In [ ]:
y_test.mean()

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score
mae = mean_absolute_error(y_test, predictions_test)
print(mae)

In [ ]:
# when and how i need to Remove the variable I need to predict? from test and validation part?

In [ ]:
## VALIDATION

In [ ]:
fifa_valid = pd.read_csv('fifa21_validate.csv')
display(fifa_valid.head())
fifa_valid.shape

In [ ]:
fifa_valid = pd.read_csv('fifa21_validate.csv')
display(fifa_valid.head())
fifa_valid.shape

In [ ]:
fifa_valid = pd.read_csv('fifa21_validate.csv')
display(fifa_valid.head())
fifa_valid.shape

In [ ]:
#def clean_data(df):
    #df.columns=[e.lower() for e in df.columns]
    #df=df.drop(columns=['position', 'wage', 'growth', 'value', 'id', 'name', 'nationality', 'club', 'team & contract', "joined", "loan date end", "release clause", "contract", "a/w", "d/w"], axis=1])
    #df.median_composure = fifa_valid['composure'].median()
    #df['composure'] = fifa_valid['composure'].fillna(df.median_composure)
    #df=df.dropna()

In [ ]:
fifa_valid = fifa_valid.drop(columns=['Wage', 'Growth', 'Value', 'ID', 'Name', 'Nationality', 'Position', 'Club', 'Team & Contract', "Joined", "Loan Date End", "Release Clause", "Contract", "A/W", "D/W"], axis=1)

In [ ]:
cols2 = []
for column in fifa_valid.columns:
    cols2.append(column.lower())
cols2
fifa_valid.columns = cols2

fifa_valid.head()

In [ ]:
fifa_valid['w/f'] = fifa_valid['w/f'].str.rstrip("★").astype(float)
fifa_valid['sm'] = fifa_valid['sm'].str.rstrip("★").astype(float)
fifa_valid['ir'] = fifa_valid['ir'].str.rstrip("★").astype(float)
fifa_valid

In [ ]:
fifa_valid['height'] = (fifa_valid['height'].str.extract(r'(\d+)\'\s*(\d+)"').astype(float).mul([12*2.54, 2.54]).sum(axis=1))

In [ ]:
fifa_valid['weight'] = fifa_valid['weight'].str.rstrip("lbs").astype(float)/2.2

In [ ]:
cols2 = ['ls','st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk']
for col in cols2:
    fifa_valid[col] = fifa_valid[col].apply(lambda x:x.split("+")[0])

In [ ]:
fifa_valid[cols2] = fifa_valid[cols2].apply(pd.to_numeric, errors='coerce')

In [ ]:
fifa_valid['hits'] = fifa_valid['hits'].apply(pd.to_numeric, errors='coerce')

In [ ]:
fifa_valid['height'] = (fifa_valid['height'].str.extract(r'(\d+)\'\s*(\d+)"').astype(float).mul([12*2.54, 2.54]).sum(axis=1))

In [ ]:
## 12.15
nulls_df = pd.DataFrame(round(fifa_valid.isna().sum()/len(fifa1),4)*100)
nulls_df
nulls_df = nulls_df.reset_index()
nulls_df
nulls_df.columns = ['header_name', 'percent_nulls']
nulls_df

In [ ]:
fifa1['composure'].value_counts(dropna=False)

In [ ]:
median_composure = fifa1['composure'].median()
median_composure

In [ ]:
fifa1['composure'] = fifa1['composure'].fillna(median_composure)

In [ ]:
fifa1.isna().sum().sum()

In [ ]:
fifa1= fifa1.dropna()
fifa1

In [ ]:
X_valid_num = fifa_valid.select_dtypes(include = np.number)
X_valid_cat = fifa_valid.select_dtypes(include = object)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
MinMaxtransformer = MinMaxScaler().fit(X_num)#Training
X_normalized = MinMaxtransformer.transform(X_num) # Implementing
print(type(X_normalized))
X_normalized = pd.DataFrame(X_normalized,columns=X_num.columns)
display(X_normalized.head())
print(type(X_normalized))

In [ ]:
x_valid_num = fifa

In [ ]:
encoder = OneHotEncoder(drop='first').fit(X_valid_cat)

cols = encoder.get_feature_names_out(input_features=X_cat.columns)

X_cat_encode1 = pd.DataFrame(encoder.transform(X_valid_cat).toarray(),columns=cols)

X_cat_encode1.head()

In [ ]:
transformer = MinMaxScaler().fit(X_valid_num) 
x_normalized2 = transformer.transform(X_valid_num)
print(x_normalized2.shape)
x_normalized3 = pd.DataFrame(x_normalized2, columns=X_valid_num.columns)
x_normalized3

### Encoding Categorical Data.

### Splitting into train set and test set.

## Modeling.

### Apply model.

## R2

### MSE.

### RMSE.

### MAE.